### PR TITLE
Refactor/results

### PR DESCRIPTION
**Pull request by rayrutjes**
~Missing docs.~

### CODE REVIEW

**Comment by rayrutjes** [comment]
So the problem with `is="ais-results"` is that `thead` gets replaced with the component div:
image

That being said, you make me realize that my solution is probably not good either for in-dom templates, because we now have <ais-results> under <table> which would get removed by browsers.

I'm not sure there is a solution here actually. Because even if we use `is` in conjunction to specifying a `tbody` tag, we would then need to pass a <template> instead of a <tr> :/

**Comment by Haroenv** [comment]
Is it possible to do something like:

```html
<table>
  <tbody is="ais-results”>
    <tr is=“template" scope="{ result }">
      <td>{{ result.name }}</td>
      <td>{{ result.description }}</td>
    </tr>
  </tbody>
</table>
```

**Comment by rayrutjes** [comment]
Nope, just tried, but nice attempt.

**Comment by rayrutjes** [comment]
The issue is the `<template>` tag.

**Comment by Haroenv** [comment]
Yeah, that’s what I found too now. Maybe ask on the forum?

**Comment by rayrutjes** [comment]
Only clean solution would be to have let the users use the `searchStore.results` directly.

**Comment by rayrutjes** [comment]
I found the solution:

```
<ais-results inline-template>
        <table>
          <tbody>
            <tr v-for="result in results" :key="result.objectID">
              <td>{{ result.name }}</td>
              <td>{{ result.description }}</td>
            </tr>
          </tbody>
        </table>
      </ais-results>
```

This overrides the default template but keeps the actual scope of the component.
Makes it very hard to reason about the scope but I guess this exists for this kind of use cases.

**Comment by rayrutjes** [comment]
I guess that it makes this PR useless.

**Pull request closed without merging**
