### PR TITLE
Only show pagination when there are multiple pages

### PR DESCRIPTION
**Pull request by juukie**
Makes sence to me 😉

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hoi @juukie ,

The current condition is a design choice.
We wanted to let users know that if they were multiple pages, they would see them.

It think hiding pagination could otherwise be misleading.

Does that make sense to you?

**Comment by juukie** [comment]
I can understand that @rayrutjes. Then leave it as is although I personnaly prefer to hide it.

**Comment by skyrpex** [comment]
What about adding the condition to a 'show' computed property? This would allow easy overriding using the extends keyword

**Comment by rayrutjes** [comment]
Yes @skyrpex , I'm all in for a way to override this.
Exposing a computed property is one way.

Other solution would be to accept a function as a callback?

Feel free to do a PR in the direction you feel most suitable and we'll discuss it.

Eventually i'd like to apply the logic on all components so that every event handler and other methods can be overridden with ease.

**Pull request closed without merging**
