### PR TITLE
fix(component): avoid raising injection failure warning

### PR DESCRIPTION
**Pull request by rayrutjes**
Closes: #196

### CODE REVIEW

**Comment by rayrutjes** [comment]
Yes, actually we should separate concerns between bem utility and search store context retrieval.
The powered by does not require the search store.

**Comment by rayrutjes** [comment]
Last commit fixes the powered by issue @Haroenv and makes the search store optional there.
I the future, I will refactor a bit the Component mixing and extract the bem classes utility functions.

**Comment by Haroenv** [comment]
Since poweredBy is the only component not _needing_ the searchStore, this seems like a reasonable tradeoff

**Comment by rayrutjes** [comment]
Yes, for now, but I keep in mind that we can do better 👍

**Pull request merged**
