### PR TITLE
chore(release): v2.7.0

### PR DESCRIPTION
**Pull request by Haroenv**

### CODE REVIEW

**Comment by Haroenv** [comment]
@yannickcr the e2e tests still seem to fail here, but a different reason now

**Comment by yannickcr** [comment]
I re-ran them, we'll see how it goes.

**Comment by Haroenv** [comment]
that was already the second run

**Comment by yannickcr** [comment]
I ran it 4 times, still failing... :neutral_face: I'll try to debug it.

**Pull request merged**
