### PR TITLE
feat(v2): major rewrite 🐕

### PR DESCRIPTION
**Pull request by Haroenv**
# See https://github.com/algolia/vue-instantsearch/pull/554 instead

### CODE REVIEW

**Comment by michelemarrionline** [comment]
waiting for this <3

**Comment by Haroenv** [comment]
Did you try out the alpha already @michelemarrionline, I’d love to have your opinion ?

**Comment by michelemarrionline** [comment]
> Did you try out the alpha already @michelemarrionline, I’d love to have your opinion ?

how can i? there's no branch for that.

**Comment by Haroenv** [comment]
It's written in the main post, `npm install vue-instantsearch@alpha` or `yarn add vue-instantsearch@alpha`. 

Note that it's definitely an alpha, and thus is still missing some of the features

**Comment by Haroenv** [comment]
Todo alpha 2: 

- class-names
- Algolia agent

**Pull request closed without merging**
