### PR TITLE
chore(vue 3): add non-ssr examples

### PR DESCRIPTION
**Pull request by eunjae-lee**
## Summary

This PR adds two examples for non-ssr usage (Vue CLI + vite).

### CODE REVIEW

**Comment by Haroenv** [comment]
should these maybe live in doc-code-samples so they don't slow down netlify as much (or ignored from the build)

**Comment by eunjae-lee** [comment]
> should these maybe live in doc-code-samples so they don't slow down netlify as much (or ignored from the build)

Yeah I wasn't sure if this should go there or here. I'll move it over there.

**Comment by eunjae-lee** [comment]
@Haroenv but what about ssr examples we already have in this repo? does it also make sense to move them over doc-code-samples?

**Comment by Haroenv** [comment]
Yes, I think probably all examples should move to doc-code-samples, except e-commerce as it's used for e2e

**Pull request closed without merging**
