### PR TITLE
fix(vue 3): fix Panel

### PR DESCRIPTION
**Pull request by eunjae-lee**
## Summary

This PR fixes an issue to make Panel widget work in Vue 3.

(Even though it's in Vue 3, it tried to access $scopedSlots which doesn't exist any more.)

### CODE REVIEW

**Comment by Haroenv** [comment]
how come the tests fail again @eunjae-lee ?

**Review by Haroenv — CHANGES_REQUESTED** [review]
this should probably get tests added

**Comment by eunjae-lee** [comment]
> how come the tests fail again @eunjae-lee ?

This branch was outdated. Now it's up-to-date.

> this should probably get tests added

I think once we run unit tests for both vue 2 and vue 3, this will be covered.

**Review by Haroenv — APPROVED** [review]
good point, the code is already correct

**Pull request merged**
