### PR TITLE
fix dom

### PR DESCRIPTION
**Pull request by JonasBa**
Duplicate of [this](https://github.com/algolia/react-instantsearch/pull/610) :)
cc @maxiloc

### CODE REVIEW

**Comment by Haroenv** [comment]
This seems pretty weird, I assumed pug would do it automatically. IS there some output comparison?

**Comment by JonasBa** [comment]
Haven't tested, but as far as the pug docs go, I can't find anywhere a documentation explaining that pug does this by default.

**Comment by JonasBa** [comment]
Thanks a lot \o/ I might make build an automated testing script to check dom validity, visual regressions testing and possibly contrast issues, so we avoid this in the future :/

**Comment by rayrutjes** [comment]
Arf, this is bad usage of pug, see #362

**Pull request merged**
