### PR TITLE
fix(server): make vue-server-renderer not a dependency

### PR DESCRIPTION
**Pull request by Haroenv**
this is done by making this dependency-injected to prevent the dependency being required for everyone

this is a breaking change, but I think I'll release it as 3.1.0 and will deprecate 3.0.0 & 3.0.1 as soon as this is merged and released Monday

### CODE REVIEW

**Comment by Haroenv** [comment]
`npm deprecate`

**Comment by yannickcr** [comment]
It may be possible to put it in `optionalDependencies` and load it conditionally. This way we keep the current API and can enforce a specific version without requiring it explicitly?

**Comment by Haroenv** [comment]
that only  works in commonjs, but the problem is for the esm build

**Comment by yannickcr** [comment]
What is not working in the esm build ?

**Pull request merged**
